version: '3.8'

services:
  # Service untuk Database MySQL
  db:
    image: mysql:8.0
    container_name: kitversity-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kikqthksbu
      MYSQL_DATABASE: kitversity
      MYSQL_USER: kitversity_user
      MYSQL_PASSWORD: kikqthksbu
    volumes:
      - db-data:/var/lib/mysql
    ports:
      # Port 3306 di VPS akan terhubung ke port 3306 di container
      - "3306:3306"

  # Service untuk Aplikasi Next.js
  app:
    container_name: kitversity-app
    build: .
    restart: always
    ports:
      # Port 3000 di VPS akan terhubung ke port 3000 di container
      - "3000:3000"
    depends_on:
      - db
    # Menggunakan environment variables dari file .env.docker
    env_file:
      - .env.docker

volumes:
  db-data: